### ISSUE TITLE
Markers are not rendered

### ISSUE THREAD

**Issue by daniel** [iwilsonq/espressopedia#1]
The code in this repo seems to have less features than in the tutorial (https://blog.expo.io/building-a-coffee-map-with-react-native-and-expo-a00b8f60a4c6)

For example it doesn't render the markers on the map.
And there's no filter feature.

Maybe you have forgotten to push the latest commits?

**Comment by iwilsonq** [comment]
Hey @daniel, sorry for the late reply. you are correct, I hadn't pushed the latest code! I should definitely remember to do that next time I try to write a tutorial.

Thank you for letting me know, it has been updated!
